apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kindmelody

resources:
  - ../../base

namePrefix: prod-

images:
  - name: kindmelody/backend
    newTag: "1.0.0"
  - name: kindmelody/frontend
    newTag: "1.0.0"
  - name: kindmelody/worker
    newTag: "1.0.0"

patches:
  - target:
      kind: Deployment
      name: kindmelody-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"
  - target:
      kind: Deployment
      name: kindmelody-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Deployment
      name: kindmelody-worker
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "4000m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "8Gi"
  - target:
      kind: HorizontalPodAutoscaler
      name: kindmelody-backend-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 50
  - target:
      kind: HorizontalPodAutoscaler
      name: kindmelody-worker-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 100
