apiVersion: v1
kind: Service
metadata:
  name: kindmelody-backend
  namespace: kindmelody
  labels:
    app: kindmelody
    component: backend
spec:
  type: ClusterIP
  selector:
    app: kindmelody
    component: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP