apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kindmelody-worker-hpa
  namespace: kindmelody
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kindmelody-worker
  minReplicas: 3
  maxReplicas: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60