apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kindmelody.fullname" . }}-secrets
  labels:
    {{- include "kindmelody.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.backend.secrets.SECRET_KEY | quote }}
